version: '3.5'
services:
    mysql:
        container_name: mysql
        image: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_DATABASE=drupal
          - MYSQL_USER=drupal
          - MYSQL_PASSWORD=drupal
        ports:
          - 33060:3306
        volumes:
          - ./docker/init:/docker-entrypoint-initdb.d
        networks:
          - drupal
    drupal:
        container_name: drupal
        build: ./docker/drupal
        ports:
          - 8000:80
        volumes:
          - ./:/var/www/html
        networks:
          - drupal
networks:
  drupal:
    name: drupal
